### ISSUE TITLE
Typo in Getting Started... article:

### ISSUE THREAD

**Issue by ncooke3** [peterfriese/SwiftUI-Concurrency-Essentials#2]
**Describe the bug**
Typo in _Getting Started with async/await in SwiftUI_ article.

**To Reproduce**
The fourth bullet in the _Calling asynchronous code from SwiftUI …_ section. See [here](https://peterfriese.dev/swiftui-concurrency-essentials-part1/#:~:text=respponse).
_resp**p**onse_ → _response_

**Comment by peterfriese** [comment]
Fixed. Thanks, Nick!
